<a href="https://colab.research.google.com/github/rujuldwivedi/Projects/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Derivative Test using Mean Squared Loss Function

In [2]:
# @markdown Importing Packages and Libraries

# @markdown Setting values

import numpy as np
n=100
d=3
h = 0.001
np.random.seed(42)
X = np.random.randn(n,d)
W = np.random.randn(d,1)
B = np.random.randn(n,1)
Y = np.random.randn(n,1)


In [3]:
# @markdown Loss Function

def Loss (X,W,B,Y):
  P = X@W
  Q = P+B-Y
  L = (Q.T@Q)/2
  return L

In [4]:
# @markdown Derivative of Loss function with respect to the given input variable using First Principal Rule

def delLX (L,X,n,d):
  delOp = np.empty((n,d))
  for i in range(n):
    for j in range(d):
      X_h = np.copy(X)
      X_h[i,j]  = X_h[i,j] + h
      L_h = Loss(X_h,W,B,Y)
      delOp[i,j] = (L_h - L)/h
  print(f"The derivative 'del L/del X' matrix from first principal is: {delOp}")

In [5]:
# @markdown Derivative of Loss function with respect to the given weights using First Principal Rule

def delLW (L,W,d):
  delOp = np.empty(d)
  for i in range(d):
    W_h = np.copy(W)
    W_h[i]  += h
    L_h = Loss(X,W_h,B,Y)
    L = Loss(X,W,B,Y)
    delOp[i] = (L_h - L)/h
  print(f"The derivative 'del L/del W' vector from first principal is: {delOp}")

In [6]:
# @markdown Derivative of Loss function with respect to the given bias using First Principal Rule

def delLB (L,B,n):
  delOp = np.empty(n)
  for i in range(n):
    B_h = np.copy(B)
    B_h[i]  += h
    L_h = Loss(X,W,B_h,Y)
    L = Loss(X,W,B,Y)
    delOp[i] = (L_h - L)/h
  print(f"The derivative 'del L/del B' vector from first principal is: {delOp}")

In [7]:
# @markdown Derivative of Loss function with respect to the given input variable using Formula

def printDelLX ():
  delLX_f =((X@W) +B - Y)@W.T
  print(f"The derivative 'del L/del W' vector from formula is: {delLX_f}")

In [8]:
# @markdown Derivative of Loss function with respect to the given weights using Formula

def printDelLW ():
  delLW_f = X.T@((X@W) + B - Y)
  print(f"The derivative 'del L/del W' vector from formula is: {delLW_f}")

In [9]:
# @markdown Derivative of Loss function with respect to the given bias using Formula

def printDelLB ():
  delLB_f = ((X@W) +B  - Y)
  print(f"The derivative 'del L/del B' vector from formula is: {delLB_f}")

In [10]:
# @markdown Printing the derivatives or the Jacobian of the Loss Function with respect to given input variable, weights and bias

L = Loss(X,W,B,Y)
delLX(L,X,n,d)
printDelLX()
delLW(L,W,d)
printDelLW()
delLB(L,B,n)
printDelLB()

The derivative 'del L/del X' matrix from first principal is: [[-0.59079835 -0.39929848  0.53316134]
 [ 0.72755549  0.4915595  -0.65526245]
 [ 2.15193359  1.4540618  -1.93926131]
 [-1.49770566 -1.0121276   1.35068861]
 [ 0.71909404  0.4858418  -0.64763492]
 [-1.40491826 -0.94942789  1.26704585]
 [-1.59342553 -1.07680888  1.43697483]
 [ 1.52955911  1.03350151 -1.3782248 ]
 [-1.45242258 -0.98152824  1.3098684 ]
 [-1.79572735 -1.21351132  1.61933885]
 [ 0.84015943  0.56764994 -0.75676874]
 [-0.39500341 -0.26699297  0.35666292]
 [-0.58125326 -0.39284853  0.52455696]
 [ 1.09296612  0.7384803  -0.98466013]
 [ 1.05008921  0.70950686 -0.94600895]
 [-0.65426252 -0.44218345  0.59037081]
 [-0.61915454 -0.41845976  0.55872289]
 [ 0.67035398  0.45290643 -0.60369843]
 [ 2.62303897  1.77240425 -2.36393702]
 [-0.19076471 -0.1289817   0.17255291]
 [-0.65895194 -0.44535226  0.59459807]
 [ 0.08440045  0.05695706 -0.07549341]
 [ 2.33399438  1.57708667 -2.10337914]
 [-2.9879789  -2.01915756  2.69408833]
 [ 